---
version: 2
sources:
- name: "prophecy_field_abhinav_demos"
  database: "prophecy-field"
  schema: "abhinav_demos"
  tables:
  - name: "customers"
    config:
      tags:
      - "pipeline:a"
      - "pipeline:b"
    columns:
    - name: "customer_id"
      dataType:
        type: "Integer"
    - name: "first_name"
      dataType:
        type: "String"
    - name: "last_name"
      dataType:
        type: "String"
    - name: "phone"
      dataType:
        type: "String"
    - name: "email"
      dataType:
        type: "String"
    - name: "country_code"
      dataType:
        type: "String"
    - name: "account_open_date"
      dataType:
        type: "Date"
    - name: "account_flags"
      dataType:
        type: "String"
    type: "table"
  - name: "orders"
    config:
      tags:
      - "pipeline:a"
      - "pipeline:b"
    columns:
    - name: "order_id"
      dataType:
        type: "Integer"
    - name: "customer_id"
      dataType:
        type: "Integer"
    - name: "order_status"
      dataType:
        type: "String"
    - name: "order_category"
      dataType:
        type: "String"
    - name: "order_date"
      dataType:
        type: "Date"
    - name: "amount"
      dataType:
        type: "Float"
    type: "table"
